version: "3"

services:
  django-1:
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
